# Generated by Django 6.0.6 on 2026-06-27 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contest', '0002_alter_competition_options_alter_contest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LapTimerDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='MAC address, used as unique device identifier.', max_length=17, unique=True)),
                ('friendly_name', models.CharField(help_text='Human-readable name set by operator on device web page.', max_length=100)),
                ('device_type', models.CharField(choices=[('LAPTIMER', 'Lap Timer'), ('ROBOT', 'Robot')], default='LAPTIMER', max_length=10)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('ERROR', 'Error')], default='OFFLINE', max_length=10)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('organisation', models.CharField(blank=True, help_text='School or organisation.', max_length=200)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='LapEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_utc', models.DateTimeField(help_text='Hardware timestamp from device (UTC, ISO 8601).')),
                ('sequence', models.PositiveIntegerField(help_text='Monotonically increasing per-device counter for deduplication.')),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='Server receive time (for latency measurement).')),
                ('competition', models.ForeignKey(help_text='Category (Competition) this event belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='lap_events', to='contest.competition')),
                ('run', models.ForeignKey(blank=True, help_text='The Run this event is assigned to (set by server).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lap_events', to='contest.run')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lap_events', to='devices.laptimerdevice')),
            ],
            options={
                'ordering': ['timestamp_utc'],
                'unique_together': {('device', 'sequence')},
            },
        ),
    ]
