# Generated by Django 6.0.6 on 2026-06-27 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_alter_competition_options_alter_contest_options_and_more'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapevent',
            name='competition',
            field=models.ForeignKey(blank=True, help_text='Category assigned by scoring logic after the run. Null for raw unprocessed events.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lap_events', to='contest.competition'),
        ),
    ]
