# Generated by Django 6.0.6 on 2026-06-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_lapevent_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='lapevent',
            name='lap_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0=start crossing, 1=first lap, 2=second lap, etc. Set by scoring engine.', null=True),
        ),
    ]
