# Generated by Django 6.0.6 on 2026-06-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_add_lap_number_to_lapevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptimerdevice',
            name='registration_status',
            field=models.CharField(choices=[('PENDING', 'Pending approval'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='PENDING', help_text='Approval state: PENDING=awaiting admin approval, ACTIVE=approved, INACTIVE=deactivated.', max_length=10),
        ),
    ]
