# Generated by Django 6.0.6 on 2026-06-27 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='contest',
            options={'verbose_name': 'Competition', 'verbose_name_plural': 'Competitions'},
        ),
        migrations.AddField(
            model_name='competition',
            name='competition_type',
            field=models.CharField(choices=[('TIMED', 'Timed (hardware lap timer)'), ('JUDGED', 'Judged (manual score entry)')], default='JUDGED', help_text='TIMED: scored by hardware lap timer. JUDGED: scored manually by a judge.', max_length=8),
        ),
        migrations.AddField(
            model_name='competition',
            name='num_laps',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of laps per run (TIMED only).'),
        ),
        migrations.AddField(
            model_name='competition',
            name='num_runs',
            field=models.PositiveSmallIntegerField(default=3, help_text='Maximum number of runs allowed per team.'),
        ),
        migrations.AddField(
            model_name='competition',
            name='state',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('READY', 'Ready to start'), ('RUNNING', 'Run in progress'), ('FINISHED', 'Finished')], default='WAITING', help_text='Current operational state of this category.', max_length=10),
        ),
        migrations.AddField(
            model_name='competition',
            name='timeout_seconds',
            field=models.PositiveSmallIntegerField(default=120, help_text='Run timeout in seconds (TIMED only).'),
        ),
        migrations.AddField(
            model_name='contest',
            name='points_table',
            field=models.JSONField(blank=True, default=dict, help_text='Position to points mapping, e.g. {1:10,2:8,3:6,4:4,5:2}.'),
        ),
        migrations.AddField(
            model_name='run',
            name='is_best',
            field=models.BooleanField(default=False, help_text="True if this is the team's best run in this category (denormalised for display speed)."),
        ),
        migrations.AddField(
            model_name='run',
            name='penalty_time_ms',
            field=models.PositiveIntegerField(default=0, help_text='Penalty time in milliseconds added to time_ms.'),
        ),
        migrations.AddField(
            model_name='run',
            name='state',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'In progress'), ('COMPLETED', 'Completed'), ('VOIDED', 'Voided (MQTT lost)'), ('MANUAL', 'Manual entry (fallback)')], default='PENDING', help_text='Lifecycle state of this run.', max_length=10),
        ),
        migrations.AddField(
            model_name='run',
            name='time_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Elapsed time in milliseconds from hardware LapEvents (TIMED runs).', null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='contest',
            field=models.ForeignKey(help_text='Parent competition event.', on_delete=django.db.models.deletion.CASCADE, to='contest.contest'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Rules of the competition and description of the task.'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(help_text='Name of the category.', max_length=200),
        ),
        migrations.AlterField(
            model_name='competition',
            name='runs',
            field=models.ManyToManyField(help_text='Teams that have runs in this category.', related_name='runs', through='contest.Run', to='contest.team'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='token',
            field=models.CharField(blank=True, default='', help_text='Token for run submissions.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Short description, e.g. time and place.'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(help_text='Name of the contest.', max_length=200),
        ),
        migrations.AlterField(
            model_name='result',
            name='comment',
            field=models.TextField(blank=True, default='', help_text='Comment to the participation.'),
        ),
        migrations.AlterField(
            model_name='result',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.competition'),
        ),
        migrations.AlterField(
            model_name='result',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.team'),
        ),
        migrations.AlterField(
            model_name='run',
            name='competition',
            field=models.ForeignKey(help_text='Source category.', on_delete=django.db.models.deletion.CASCADE, to='contest.competition'),
        ),
        migrations.AlterField(
            model_name='run',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in whole seconds (legacy, kept for compatibility).'),
        ),
        migrations.AlterField(
            model_name='run',
            name='judge_comment',
            field=models.CharField(blank=True, help_text='Comment by a judge.', max_length=200),
        ),
        migrations.AlterField(
            model_name='run',
            name='score',
            field=models.IntegerField(blank=True, help_text='Assigned by a judge (JUDGED runs).', null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='team',
            field=models.ForeignKey(help_text='Who performed the run.', on_delete=django.db.models.deletion.CASCADE, to='contest.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='contest',
            field=models.ForeignKey(help_text='A team belongs to a contest.', on_delete=django.db.models.deletion.CASCADE, to='contest.contest'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Team members and affiliation.'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='Identifier of the team.', max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='token',
            field=models.CharField(blank=True, default='', help_text='Token for run submissions.', max_length=200, null=True, unique=True),
        ),
    ]
