# Generated by Django 6.0.6 on 2026-06-27 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_alter_competition_options_alter_contest_options_and_more'),
        ('devices', '0002_alter_lapevent_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='lap_timer',
            field=models.ForeignKey(blank=True, help_text='Lap timer device assigned to time this category (TIMED only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='devices.laptimerdevice'),
        ),
    ]
