# Generated by Django 6.0.6 on 2026-06-29 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_add_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='team_name',
            field=models.CharField(blank=True, default='', help_text='Team name for Participant accounts. Appears in all competition results.', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='requested_role',
            field=models.CharField(choices=[('judge', 'Judge'), ('organiser', 'Organiser'), ('participant', 'Participant / Team')], default='judge', max_length=16),
        ),
        migrations.CreateModel(
            name='ContestRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='contest.contest')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='contest.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Competition registration',
                'verbose_name_plural': 'Competition registrations',
                'unique_together': {('user', 'contest')},
            },
        ),
    ]
