# Generated by Django 6.0.6 on 2026-06-27 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contest', '0003_competition_lap_timer'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('is_eligible', models.BooleanField(default=False)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contest')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.team')),
            ],
            options={
                'unique_together': {('contest', 'team')},
            },
        ),
    ]
